// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var Curry          = require("bs-platform/lib/js/curry.js");
var Caml_oo_curry  = require("bs-platform/lib/js/caml_oo_curry.js");
var CamlinternalOO = require("bs-platform/lib/js/camlinternalOO.js");

function abstractProductA_init($$class) {
  var methodA = CamlinternalOO.get_method_label($$class, "methodA");
  CamlinternalOO.set_method($$class, methodA, (function () {
          return "yelo";
        }));
  return (function (_, self) {
      return CamlinternalOO.create_object_opt(self, $$class);
    });
}

var abstractProductA = CamlinternalOO.make_class(["methodA"], abstractProductA_init);

var tmp = Curry._1(abstractProductA[0], 0);

console.log(Caml_oo_curry.js1(641535552, 1, tmp));

exports.abstractProductA = abstractProductA;
/* abstractProductA Not a pure module */
